# Generated by Django 5.2.4 on 2025-07-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_material', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classresource',
            options={'verbose_name': '5. Class Resource', 'verbose_name_plural': '5. Class Resources'},
        ),
        migrations.AlterModelOptions(
            name='recording',
            options={'verbose_name': '4. Recording', 'verbose_name_plural': '4. Recordings'},
        ),
        migrations.AlterField(
            model_name='classresource',
            name='class_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classresource',
            name='external_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='classresource',
            name='minio_browser_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='classresource',
            name='object_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='recording',
            name='class_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='recording',
            name='minio_browser_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='object_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterModelTable(
            name='classresource',
            table=None,
        ),
        migrations.AlterModelTable(
            name='recording',
            table=None,
        ),
    ]
