# Generated by Django 5.2.4 on 2025-07-19 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_material", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batch",
            options={
                "ordering": ["start_date"],
                "verbose_name": "2. Batch Management",
                "verbose_name_plural": "2. Batch Management",
            },
        ),
        migrations.AlterModelOptions(
            name="classresource",
            options={
                "ordering": ["class_date", "uploaded_at"],
                "verbose_name": "4. Class Resource Management",
                "verbose_name_plural": "4. Class Resource Management",
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "1. Course Management",
                "verbose_name_plural": "1. Course Management",
            },
        ),
        migrations.AlterModelOptions(
            name="instructor",
            options={
                "verbose_name": "6. Instructor Management",
                "verbose_name_plural": "6. Instructors Management",
            },
        ),
        migrations.AlterModelOptions(
            name="recording",
            options={
                "ordering": ["-class_date", "-uploaded_at"],
                "verbose_name": "3. Recording Management",
                "verbose_name_plural": "3. Recording Management",
            },
        ),
        migrations.RemoveField(
            model_name="classresource",
            name="is_downloadable",
        ),
        migrations.RemoveField(
            model_name="recording",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="recording",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="recording",
            name="recording_url",
        ),
    ]
