# Generated by Django 5.2.4 on 2025-07-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "course_material",
            "0002_alter_batch_options_alter_classresource_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exam",
            options={
                "ordering": ["start_datetime"],
                "verbose_name": "5. Exam Management",
                "verbose_name_plural": "5. Exam Management",
            },
        ),
        migrations.AlterModelOptions(
            name="instructor",
            options={
                "verbose_name": "7. Instructor Management",
                "verbose_name_plural": "7. Instructors Management",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["order"],
                "verbose_name": "6. Question Management",
                "verbose_name_plural": "6. Question Management",
            },
        ),
        migrations.RemoveField(
            model_name="classresource",
            name="resource_type",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="passing_marks",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="show_result_immediately",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="shuffle_questions",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="total_marks",
        ),
        migrations.AlterField(
            model_name="exam",
            name="duration",
            field=models.PositiveBigIntegerField(help_text="Duration in minutes"),
        ),
    ]
