# Generated by Django 5.2.4 on 2025-07-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "course_material",
            "0005_alter_batch_options_alter_classresource_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "Question", "verbose_name_plural": "Questions"},
        ),
        migrations.RemoveField(
            model_name="answer",
            name="order",
        ),
        migrations.RemoveField(
            model_name="question",
            name="order",
        ),
    ]
