# Generated by Django 5.2.4 on 2025-07-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "course_material",
            "0006_alter_answer_options_alter_question_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrollment",
            options={
                "ordering": ["-enrollment_date"],
                "verbose_name": "7. Enrollment",
                "verbose_name_plural": "7. Enrollments",
            },
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="completion_date",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="status",
        ),
    ]
