# Generated by Django 5.2.4 on 2025-07-20 06:02

import course_material.minio_backend
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_material', '0007_alter_enrollment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classresource',
            name='file',
            field=models.FileField(blank=True, null=True, storage=course_material.minio_backend.MinioStorage(), upload_to='resources/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'pptx', 'txt', 'csv', 'xlsx', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='recording',
            name='recording_file',
            field=models.FileField(blank=True, null=True, storage=course_material.minio_backend.MinioStorage(), upload_to='recordings/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv'])]),
        ),
    ]
