# Generated by Django 5.2.4 on 2025-07-20 06:24

import course_material.minio_backend
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_material', '0008_alter_classresource_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='demo_video',
            field=models.FileField(blank=True, null=True, storage=course_material.minio_backend.MinioStorage(), upload_to='recordings/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv'])]),
        ),
    ]
