# Generated by Django 5.2.4 on 2025-07-20 15:11

import course_material.minio_backend
import course_material.models.class_resources
import course_material.models.course
import course_material.models.recording
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_material', '0010_coursedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructors',
        ),
        migrations.AddField(
            model_name='batch',
            name='instructors',
            field=models.ManyToManyField(related_name='courses', to='course_material.instructor'),
        ),
        migrations.AlterField(
            model_name='classresource',
            name='file',
            field=models.FileField(blank=True, null=True, storage=course_material.minio_backend.MinioStorage(), upload_to=course_material.models.class_resources.upload_to_batch_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'pptx', 'txt', 'csv', 'xlsx', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='course',
            name='demo_video',
            field=models.FileField(blank=True, null=True, storage=course_material.minio_backend.MinioStorage(), upload_to=course_material.models.course.upload_to_demo_video, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv'])]),
        ),
        migrations.AlterField(
            model_name='recording',
            name='recording_file',
            field=models.FileField(blank=True, null=True, storage=course_material.minio_backend.MinioStorage(), upload_to=course_material.models.recording.upload_to_recording_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv'])]),
        ),
    ]
