"""
Django settings for sma_backend project.

Generated by 'django-admin startproject' using Django 5.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

ROOT_URLCONF = "sma_backend.urls"

WSGI_APPLICATION = "sma_backend.wsgi.application"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


from sma_backend.conf.authorization import AUTH_USER_MODEL
from sma_backend.conf.databases import DATABASES
from sma_backend.conf.djoser import DJOSER
from sma_backend.conf.email_conf import *
from sma_backend.conf.installed_apps import INSTALLED_APPS
from sma_backend.conf.middleware import MIDDLEWARE
from sma_backend.conf.rest_confs import REST_FRAMEWORK, SIMPLE_JWT
from sma_backend.conf.security import *
from sma_backend.conf.templates import TEMPLATES
from sma_backend.conf.timezone_conf import *
