import course_material.admin_reg.admin_entries.class_resources
import course_material.admin_reg.admin_entries.course
import course_material.admin_reg.admin_entries.exam
import course_material.admin_reg.admin_entries.instructor
import course_material.admin_reg.admin_entries.recording
import course_material.admin_reg.admin_entries.enrollment