name: SMA Backend Development Environment

on:
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: bitnova-runner

    steps:
      - name: Check Docker Compose Version
        run: docker-compose --version
      
      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push the latest images
        run: |
          cd /home/ubuntu/deploy/sma-backend-docker/
          docker-compose -f docker-compose.dev.yml push

      - name: Pull the latest images
        run: |
          docker-compose -f docker-compose.dev.yml pull

      - name: Deploy the application
        run: |
          docker-compose -f docker-compose.dev.yml down
          docker-compose -f docker-compose.dev.yml up -d --build
