name: SMA Backend Development Environment

on:
  pull_request:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: master
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build and Push Docker images
        run: |
          docker-compose -f docker-compose.dev.yml build
          docker-compose -f docker-compose.dev.yml push

  deploy:
    runs-on: bitnova-runner
    environment: master
    needs: build-and-push
    
    steps:
      - name: Check Docker Compose Version
        run: docker-compose --version
      
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin
        
      - name: Pull the latest images
        run: |
          cd /home/ubuntu/deploy/sma-backend-docker/
          docker-compose -f docker-compose.dev.yml pull

      - name: Deploy the application
        run: |
          cd /home/ubuntu/deploy/sma-backend-docker/
          docker-compose -f docker-compose.dev.yml down
          docker-compose -f docker-compose.dev.yml up -d --build