name: SMA Backend Development Environment

on:
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: bitnova-runner
    environment: master

    steps:
      - name: Check Docker Compose Version
        run: docker-compose --version
      
      - name: Docker Login
        run: echo "${{ vars.DOCKER_PASSWORD }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin
        
      - name: Change to deployment directory
        run: cd /home/ubuntu/deploy/sma-backend-docker/

      - name: Pull the latest images
        run: |
          cd /home/ubuntu/deploy/sma-backend-docker/
          docker-compose -f docker-compose.dev.yml pull

      - name: Deploy the application
        run: |
          cd /home/ubuntu/deploy/sma-backend-docker/
          docker-compose -f docker-compose.dev.yml down
          docker-compose -f docker-compose.dev.yml up -d --build