name: SMA Backend Development Environment

on:
  push:
    branches: [master]

jobs:
  build-and-push-dev-image:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker images
        run: docker-compose -f docker-compose.dev.yml build
        
      - name: Push Docker images
        run: docker-compose -f docker-compose.dev.yml push

  dev-pull-from-hub:
    runs-on: bitnova-runner
    environment: dev
    needs: build-and-push-dev-image

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin

      - name: Pull the latest images
        run: |
          docker-compose -f docker-compose.dev.yml pull

  deploy-to-dev:
    runs-on: bitnova-runner
    environment: dev
    needs: dev-pull-from-hub
    steps:        
      - name: Deploy the application
        run: |
          docker-compose -f docker-compose.dev.yml down --remove-orphans
          docker-compose -f docker-compose.dev.yml up -d